#!/bin/bash

selected=$(echo -e "⇠ Logout\n⏾ Suspend\n⭮ Reboot\n⏻ Shutdown" | \
    wofi --width 320 --height 200 --dmenu --cache-file /dev/null | \
    awk '{print tolower($2)}')

case $selected in
  logout)
    swaymsg exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff;;
esac

