#!/bin/bash

selected=$(echo -e "⇠ Logout\n⏾ Suspend\n⭮ Reboot\n⏻ Shutdown" | \
    wofi --dmenu --lines=5 --height=300 --width=300 --cache-file=/dev/null --prompt="" | \
    awk '{print tolower($2)}')

case $selected in
  logout)
    swaymsg exit ;;
  suspend)
    exec systemctl suspend ;;
  reboot)
    exec systemctl reboot ;;
  shutdown)
    exec systemctl poweroff ;;
esac

